
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                yy_size_t yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (yy_size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 101
#define YY_END_OF_BUFFER 102
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[333] =
    {   0,
        0,    0,  102,  100,   99,   98,  100,  100,   90,   91,
       77,   75,   85,   76,   84,   78,   67,   86,   87,   80,
       79,   81,   88,   74,   74,   74,   74,   74,   74,   74,
       74,   74,   74,   74,   74,   74,   74,   74,   74,   74,
       74,   74,   74,   74,   74,   82,   83,   89,  100,   98,
        0,    0,   71,   96,    0,   67,    0,   95,   93,   92,
       94,   74,   74,   74,   74,   74,   74,   74,   74,   74,
       74,   74,   74,   10,   74,   74,   74,   74,   74,   74,
       74,   18,   74,   20,   74,   74,   74,   74,   74,   74,
       29,   74,   31,   74,   74,   74,   74,   74,   74,   74,

       74,   74,   74,   43,   74,   74,   74,   74,   74,   74,
       74,   74,   74,    0,   97,   69,   71,    0,   69,   68,
        0,   68,    1,   74,    3,   74,   74,   74,   74,   74,
       74,   74,    9,   74,   74,   74,   13,   74,   74,   15,
       74,   74,   74,   74,   74,   74,   74,   74,   25,   26,
       27,   74,   74,   74,   74,   74,   74,   74,   74,   74,
       74,   39,   40,   74,   41,   74,   74,   74,   74,   74,
       74,   74,   74,   74,   48,   74,   74,   74,   51,    0,
       70,    0,    0,   74,   74,   74,   57,    5,   65,   74,
       74,   74,   74,   12,   74,   14,   74,   17,   74,   74,

       74,   74,   74,   74,   74,   74,   74,   74,   74,   74,
       74,   62,   74,   74,   74,   38,   74,   74,   74,   74,
       42,   72,   44,   45,   74,   47,   74,   50,   58,    0,
       68,    2,    4,   74,    6,   74,   74,   74,   73,   74,
       74,   74,   74,   56,   74,   74,   24,   74,   74,   74,
       74,   74,   74,   74,   60,   74,   74,   74,   53,   74,
       74,   74,   46,   49,   74,   74,   74,   64,   11,   74,
       74,   74,   22,   74,   74,   74,   74,   28,   74,   32,
       74,   74,   35,   74,   37,   63,   74,   66,   61,   74,
       74,   74,   74,   74,   52,   74,   55,   74,   74,   74,

       34,   74,   74,   74,   74,   16,   74,   74,   74,   59,
       30,   74,   74,   54,   74,   74,   74,   21,   23,   33,
       74,   74,    8,   74,   74,    7,   74,   36,   74,   74,
       19,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    1,    1,    6,    1,    1,    1,    7,    8,
        9,   10,   11,   12,   13,   14,   15,   16,   16,   16,
       16,   17,   16,   18,   16,   16,   16,   19,   20,   21,
       22,   23,    1,   24,   25,   26,   27,   28,   29,   30,
       31,   32,   33,   34,   35,   36,   37,   38,   39,   40,
       41,   42,   43,   44,   45,   46,   47,   48,   49,   50,
       51,    1,   52,   53,   50,    1,   54,   55,   56,   57,

       58,   59,   60,   61,   62,   63,   64,   65,   66,   67,
       68,   69,   70,   71,   72,   73,   74,   75,   76,   77,
       78,   50,   79,    1,   80,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[81] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    2,    2,    2,    1,    1,
        1,    1,    1,    1,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        1,    1,    1,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    1,    1
    } ;

static yyconst flex_int16_t yy_base[337] =
    {   0,
        0,    0,  645,  678,  678,  678,  641,   78,  678,  678,
      678,  678,  678,  678,  308,  678,   70,  296,  678,   60,
      678,  258,  678,   51,   61,   66,   63,   59,  105,   64,
        0,   74,  110,   68,   75,  116,  120,  100,  119,  128,
      156,  125,  126,  167,  113,  678,  678,  678,  192,  678,
      186,  177,  109,  678,  137,  193,  202,  678,  678,  678,
      678,    0,  155,  154,  165,  172,  165,  164,  171,  191,
      183,  180,  180,  191,  187,  211,  204,  205,  200,  206,
      202,    0,  207,  217,  222,  216,  228,  221,  214,  226,
        0,  233,    0,  236,  225,  227,  269,  261,  262,  236,

      254,  239,  255,    0,  243,  259,  267,  277,  265,  279,
      270,  273,  274,  102,  678,  163,  162,  159,  111,  303,
      330,  333,    0,  299,    0,  304,  303,  313,  323,  312,
      312,  312,    0,  331,  320,  330,    0,  317,  333,    0,
      336,  325,  329,  338,  336,  361,  341,  341,    0,    0,
        0,  344,  332,  340,  349,  335,  342,  343,  357,  368,
      370,    0,    0,  366,    0,  379,  376,  380,  376,  386,
      387,  373,  385,  377,    0,  385,  390,  395,    0,  107,
      678,  102,  414,  379,  395,  405,    0,    0,    0,  391,
      394,  402,  396,    0,  419,    0,  409,    0,  425,  413,

      418,   89,  428,  422,  427,  434,  441,  439,  442,  430,
      445,    0,  433,  432,  453,    0,  435,  444,  445,  448,
        0,    0,    0,    0,  455,    0,  463,    0,    0,  495,
      500,    0,    0,  468,  452,  451,  469,  467,    0,  481,
      482,  491,  497,    0,  499,  499,    0,  492,  492,  488,
      489,  506,  508,  512,    0,  510,  497,  496,    0,  512,
      509,  513,    0,    0,  507,  501,  520,    0,    0,  510,
      521,  507,    0,  510,  529,  512,  522,    0,  533,    0,
      532,  545,    0,  545,    0,    0,  548,    0,    0,  560,
      544,  551,  552,  562,    0,  565,    0,  566,  553,  554,

        0,  569,  554,  555,  561,    0,  558,  575,  575,    0,
        0,  576,  562,    0,  569,  567,  585,    0,    0,    0,
      585,  572,    0,  578,  601,    0,  602,    0,  601,  604,
        0,  678,  671,   99,  673,  675
    } ;

static yyconst flex_int16_t yy_def[337] =
    {   0,
      332,    1,  332,  332,  332,  332,  332,  333,  332,  332,
      332,  332,  332,  332,  332,  332,  332,  332,  332,  332,
      332,  332,  332,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  332,  332,  332,  335,  332,
      336,  336,  332,  332,  332,  332,  332,  332,  332,  332,
      332,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,

      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  335,  332,  332,  332,  332,  332,  332,
      332,  332,  334,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  332,
      332,  332,  332,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,

      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  332,
      332,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,

      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      334,    0,  332,  332,  332,  332
    } ;

static yyconst flex_int16_t yy_nxt[759] =
    {   0,
        4,    5,    6,    7,    5,    4,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   17,   17,   18,   19,
       20,   21,   22,   23,   24,   25,   26,   27,   28,   29,
       30,   31,   32,   31,   31,   33,   34,   35,   36,   37,
       38,   39,   40,   41,   42,   43,   44,   45,   31,   31,
       46,   47,   48,   24,   25,   26,   27,   28,   29,   30,
       31,   32,   31,   31,   33,   34,   35,   36,   37,   38,
       39,   40,   41,   42,   43,   44,   45,   31,   49,    4,
       52,   59,   60,   55,   53,   56,   56,   56,   63,   66,
       69,   72,   64,   65,   75,   73,   76,   70,   57,   67,

       62,   74,   81,   82,   71,  244,   87,   88,   52,   68,
       83,   84,  182,   89,  118,  119,  182,   63,   66,   69,
       72,   64,   65,   75,   73,   76,   70,   57,   67,   77,
       74,   81,   82,   71,   85,   87,   88,   78,   68,   83,
       84,   90,   89,   79,   94,   91,   96,   97,   86,   80,
      109,  113,  120,  120,  120,   92,   98,   93,   77,   99,
      100,   95,  107,   85,  101,  181,   78,  108,  180,  180,
       90,  102,   79,   94,   91,   96,   97,   86,   80,  109,
      113,  115,  123,  117,   92,   98,   93,  103,   99,  100,
       95,  107,  116,  101,  104,  124,  108,  105,  110,  111,

      102,  125,  126,  127,  106,  112,   55,  128,   56,   56,
       56,  123,  121,  129,  121,  130,  103,  122,  122,  122,
      131,   57,  132,  104,  124,  133,  105,  110,  111,  136,
      125,  126,  127,  106,  112,  134,  128,  135,  137,  138,
      139,  140,  129,  141,  130,  142,  143,  147,  144,  131,
       57,  132,  145,  148,  133,  149,  150,  151,  136,  152,
      146,  153,  154,  155,  134,  156,  135,  137,  138,  139,
      140,  115,  141,  166,  142,  143,  147,  144,  167,   61,
      168,  145,  148,  169,  149,  150,  151,  170,  152,  146,
      153,  154,  155,  157,  156,  158,  161,  163,  171,  172,

      164,  159,  166,  165,  162,  174,  175,  167,  160,  168,
      173,  176,  169,  177,  178,  179,  170,   58,  120,  120,
      120,   54,  157,  184,  158,  161,  163,  171,  172,  164,
      159,  183,  165,  162,  174,  175,  185,  160,  186,  173,
      176,  187,  177,  178,  179,  122,  122,  122,  122,  122,
      122,  188,  184,  189,  190,  191,  192,  193,  194,  195,
      183,  196,  197,  198,  199,  185,  200,  186,  201,  204,
      187,  205,  206,  207,  208,  209,  211,  212,  202,  210,
      188,  213,  189,  190,  191,  192,  193,  194,  195,  203,
      196,  197,  198,  199,  214,  200,  215,  201,  204,  216,

      205,  206,  207,  208,  209,  211,  212,  217,  210,  218,
      213,  219,  220,  221,  222,  223,  224,  225,  203,  226,
      227,  228,  229,  214,  230,  215,  230,  232,  216,  231,
      231,  231,  233,  234,  235,  236,  217,  237,  218,  238,
      219,  220,  221,  222,  223,  224,  225,  239,  226,  227,
      228,  229,  240,  241,  242,  243,  232,  247,  245,  248,
      250,  233,  234,  235,  236,  251,  237,  252,  238,  246,
      253,  254,  255,  249,  256,  257,  239,  258,  259,  260,
      261,  240,  241,  242,  243,  262,  247,  245,  248,  250,
      263,  264,  265,  266,  251,  267,  252,  268,  246,  253,

      254,  255,  249,  256,  257,  269,  258,  259,  260,  261,
      231,  231,  231,  270,  262,  231,  231,  231,  271,  263,
      264,  265,  266,  272,  267,  273,  268,  274,  275,  276,
      277,  278,  279,  280,  269,  281,  282,  283,  284,  285,
      286,  287,  270,  288,  289,  290,  291,  271,  292,  293,
      294,  295,  272,  296,  273,  297,  274,  275,  276,  277,
      278,  279,  280,  298,  281,  282,  283,  284,  285,  286,
      287,  299,  288,  289,  290,  291,  300,  292,  293,  294,
      295,  301,  296,  302,  297,  303,  304,  305,  306,  307,
      308,  309,  298,  310,  311,  312,  313,  314,  315,  316,

      299,  317,  318,  319,  320,  300,  321,  322,  323,  324,
      301,  325,  302,  326,  303,  304,  305,  306,  307,  308,
      309,  327,  310,  311,  312,  313,  314,  315,  316,  328,
      317,  318,  319,  320,  329,  321,  322,  323,  324,  330,
      325,  331,  326,   50,  332,  332,  332,  332,  332,  332,
      327,  332,  332,  332,  332,  332,  332,  332,  328,  332,
      332,  332,  332,  329,  332,  332,  332,  332,  330,  332,
      331,   51,   51,  114,  114,   52,   52,    3,  332,  332,
      332,  332,  332,  332,  332,  332,  332,  332,  332,  332,
      332,  332,  332,  332,  332,  332,  332,  332,  332,  332,

      332,  332,  332,  332,  332,  332,  332,  332,  332,  332,
      332,  332,  332,  332,  332,  332,  332,  332,  332,  332,
      332,  332,  332,  332,  332,  332,  332,  332,  332,  332,
      332,  332,  332,  332,  332,  332,  332,  332,  332,  332,
      332,  332,  332,  332,  332,  332,  332,  332,  332,  332,
      332,  332,  332,  332,  332,  332,  332,  332
    } ;

static yyconst flex_int16_t yy_chk[759] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        8,   20,   20,   17,    8,   17,   17,   17,   24,   25,
       26,   27,   24,   24,   28,   27,   28,   26,   17,   25,

      334,   27,   30,   32,   26,  202,   34,   35,  182,   25,
       32,   32,  180,   35,   53,   53,  119,   24,   25,   26,
       27,   24,   24,   28,   27,   28,   26,   17,   25,   29,
       27,   30,   32,   26,   33,   34,   35,   29,   25,   32,
       32,   36,   35,   29,   37,   36,   38,   39,   33,   29,
       43,   45,   55,   55,   55,   36,   40,   36,   29,   40,
       40,   37,   42,   33,   40,  118,   29,   42,  117,  116,
       36,   40,   29,   37,   36,   38,   39,   33,   29,   43,
       45,  114,   63,   52,   36,   40,   36,   41,   40,   40,
       37,   42,   51,   40,   41,   64,   42,   41,   44,   44,

       40,   65,   66,   67,   41,   44,   56,   68,   56,   56,
       56,   63,   57,   69,   57,   70,   41,   57,   57,   57,
       71,   56,   72,   41,   64,   73,   41,   44,   44,   75,
       65,   66,   67,   41,   44,   74,   68,   74,   76,   77,
       78,   79,   69,   80,   70,   81,   83,   85,   84,   71,
       56,   72,   84,   86,   73,   87,   88,   89,   75,   90,
       84,   92,   94,   95,   74,   96,   74,   76,   77,   78,
       79,   49,   80,  100,   81,   83,   85,   84,  101,   22,
      102,   84,   86,  103,   87,   88,   89,  105,   90,   84,
       92,   94,   95,   97,   96,   97,   98,   99,  106,  107,

       99,   97,  100,   99,   98,  108,  109,  101,   97,  102,
      107,  110,  103,  111,  112,  113,  105,   18,  120,  120,
      120,   15,   97,  124,   97,   98,   99,  106,  107,   99,
       97,  120,   99,   98,  108,  109,  126,   97,  127,  107,
      110,  128,  111,  112,  113,  121,  121,  121,  122,  122,
      122,  129,  124,  130,  131,  132,  134,  135,  136,  138,
      120,  139,  141,  142,  143,  126,  144,  127,  145,  147,
      128,  148,  152,  153,  154,  155,  156,  157,  146,  155,
      129,  158,  130,  131,  132,  134,  135,  136,  138,  146,
      139,  141,  142,  143,  159,  144,  160,  145,  147,  161,

      148,  152,  153,  154,  155,  156,  157,  164,  155,  166,
      158,  167,  168,  169,  170,  171,  172,  173,  146,  174,
      176,  177,  178,  159,  183,  160,  183,  184,  161,  183,
      183,  183,  185,  186,  190,  191,  164,  192,  166,  193,
      167,  168,  169,  170,  171,  172,  173,  195,  174,  176,
      177,  178,  197,  199,  200,  201,  184,  204,  203,  205,
      206,  185,  186,  190,  191,  207,  192,  208,  193,  203,
      209,  210,  211,  205,  213,  214,  195,  215,  217,  218,
      219,  197,  199,  200,  201,  220,  204,  203,  205,  206,
      225,  227,  234,  235,  207,  236,  208,  237,  203,  209,

      210,  211,  205,  213,  214,  238,  215,  217,  218,  219,
      230,  230,  230,  240,  220,  231,  231,  231,  241,  225,
      227,  234,  235,  242,  236,  243,  237,  245,  246,  248,
      249,  250,  251,  252,  238,  253,  254,  256,  257,  258,
      260,  261,  240,  262,  265,  266,  267,  241,  270,  271,
      272,  274,  242,  275,  243,  276,  245,  246,  248,  249,
      250,  251,  252,  277,  253,  254,  256,  257,  258,  260,
      261,  279,  262,  265,  266,  267,  281,  270,  271,  272,
      274,  282,  275,  284,  276,  287,  290,  291,  292,  293,
      294,  296,  277,  298,  299,  300,  302,  303,  304,  305,

      279,  307,  308,  309,  312,  281,  313,  315,  316,  317,
      282,  321,  284,  322,  287,  290,  291,  292,  293,  294,
      296,  324,  298,  299,  300,  302,  303,  304,  305,  325,
      307,  308,  309,  312,  327,  313,  315,  316,  317,  329,
      321,  330,  322,    7,    3,    0,    0,    0,    0,    0,
      324,    0,    0,    0,    0,    0,    0,    0,  325,    0,
        0,    0,    0,  327,    0,    0,    0,    0,  329,    0,
      330,  333,  333,  335,  335,  336,  336,  332,  332,  332,
      332,  332,  332,  332,  332,  332,  332,  332,  332,  332,
      332,  332,  332,  332,  332,  332,  332,  332,  332,  332,

      332,  332,  332,  332,  332,  332,  332,  332,  332,  332,
      332,  332,  332,  332,  332,  332,  332,  332,  332,  332,
      332,  332,  332,  332,  332,  332,  332,  332,  332,  332,
      332,  332,  332,  332,  332,  332,  332,  332,  332,  332,
      332,  332,  332,  332,  332,  332,  332,  332,  332,  332,
      332,  332,  332,  332,  332,  332,  332,  332
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[102] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 
    0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexer/pascal.l"
#line 3 "lexer/pascal.l"
#define YYSTYPE char*
//#define DEBUG_LEXER 

#include <cstring>
#include "pascal.y.h"
using namespace std;

#define YY_USER_ACTION yylloc->begin.line = yylloc->end.line = yylineno-1; \
    yylloc->begin.column = yycolumn; yylloc->end.column = yycolumn+yyleng-1; \
    yycolumn += yyleng;

#ifdef DEBUG_LEXER
#define RETURN_TOKEN(X) printf(#X); printf("\n");// return (X);
#elif
#define RETURN_TOKEN(X) return(X);

#endif

/* TODO: Some of the Pascal base types here: P24 3.1*/
/* Values here*/
/* TODO: Pascal symbols here: */
/* TODO: Other tokens */
#line 778 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 129 "lexer/pascal.l"


#line 963 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 333 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 678 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			yy_size_t yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					   
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 131 "lexer/pascal.l"
{
    RETURN_TOKEN(KWD_AND)
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 135 "lexer/pascal.l"
{
    RETURN_TOKEN(KWD_ARRAY)
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 139 "lexer/pascal.l"
{
    RETURN_TOKEN(KWD_ASM)
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 143 "lexer/pascal.l"
{
    RETURN_TOKEN(KWD_BEGIN)
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 147 "lexer/pascal.l"
{
    RETURN_TOKEN(KWD_CASE)
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 151 "lexer/pascal.l"
{
    RETURN_TOKEN(KWD_CONST)
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 155 "lexer/pascal.l"
{
    RETURN_TOKEN(KWD_CONSTRUCTOR)
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 159 "lexer/pascal.l"
{
    RETURN_TOKEN(KWD_DESTRUCTOR)
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 163 "lexer/pascal.l"
{
    RETURN_TOKEN(KWD_DIV)
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 167 "lexer/pascal.l"
{
    RETURN_TOKEN(KWD_DO)
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 171 "lexer/pascal.l"
{
    RETURN_TOKEN(KWD_DOWNTO)
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 175 "lexer/pascal.l"
{
    RETURN_TOKEN(KWD_ELSE)
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 179 "lexer/pascal.l"
{
    RETURN_TOKEN(KWD_END)
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 183 "lexer/pascal.l"
{
    RETURN_TOKEN(KWD_FILE)
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 187 "lexer/pascal.l"
{
    RETURN_TOKEN(KWD_FOR)
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 191 "lexer/pascal.l"
{
    RETURN_TOKEN(KWD_FUNCTION)
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 195 "lexer/pascal.l"
{
    RETURN_TOKEN(KWD_GOTO)
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 199 "lexer/pascal.l"
{
    RETURN_TOKEN(KWD_IF)
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 203 "lexer/pascal.l"
{
    RETURN_TOKEN(KWD_IMPLEMENTATION)
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 207 "lexer/pascal.l"
{
    RETURN_TOKEN(KWD_IN)
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 211 "lexer/pascal.l"
{
    RETURN_TOKEN(KWD_INHERITED)
}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 215 "lexer/pascal.l"
{
    RETURN_TOKEN(KWD_INLINE)
}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 219 "lexer/pascal.l"
{
    RETURN_TOKEN(KWD_INTERFACE)
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 223 "lexer/pascal.l"
{
    RETURN_TOKEN(KWD_LABEL)
}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 227 "lexer/pascal.l"
{
    RETURN_TOKEN(KWD_MOD)
}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 231 "lexer/pascal.l"
{
    RETURN_TOKEN(KWD_NIL)
}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 235 "lexer/pascal.l"
{
    RETURN_TOKEN(KWD_NOT)
}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 239 "lexer/pascal.l"
{
    RETURN_TOKEN(KWD_OBJECT)
}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 243 "lexer/pascal.l"
{
    RETURN_TOKEN(KWD_OF)
}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 247 "lexer/pascal.l"
{
    RETURN_TOKEN(KWD_OPERATOR)
}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 251 "lexer/pascal.l"
{
    RETURN_TOKEN(KWD_OR)
}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 255 "lexer/pascal.l"
{
    RETURN_TOKEN(KWD_PACKED)
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 259 "lexer/pascal.l"
{
    RETURN_TOKEN(KWD_PROCEDURE)
}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 263 "lexer/pascal.l"
{
    RETURN_TOKEN(KWD_PROGRAM)
}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 267 "lexer/pascal.l"
{
    RETURN_TOKEN(KWD_RECORD)
}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 271 "lexer/pascal.l"
{
    RETURN_TOKEN(KWD_REINTRODUCE)
}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 275 "lexer/pascal.l"
{
    RETURN_TOKEN(KWD_REPEAT)
}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 279 "lexer/pascal.l"
{
    RETURN_TOKEN(KWD_SELF)
}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 283 "lexer/pascal.l"
{
    RETURN_TOKEN(KWD_SET)
}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 287 "lexer/pascal.l"
{
    RETURN_TOKEN(KWD_SHL)
}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 291 "lexer/pascal.l"
{
    RETURN_TOKEN(KWD_SHR)
}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 295 "lexer/pascal.l"
{
    RETURN_TOKEN(KWD_THEN)
}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 299 "lexer/pascal.l"
{
    RETURN_TOKEN(KWD_TO)
}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 303 "lexer/pascal.l"
{
    RETURN_TOKEN(KWD_TYPE)
}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 307 "lexer/pascal.l"
{
    RETURN_TOKEN(KWD_UNIT)
}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 311 "lexer/pascal.l"
{
    RETURN_TOKEN(KWD_UNTIL)
}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 315 "lexer/pascal.l"
{
    RETURN_TOKEN(KWD_USES)
}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 319 "lexer/pascal.l"
{
    RETURN_TOKEN(KWD_VAR)
}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 323 "lexer/pascal.l"
{
    RETURN_TOKEN(KWD_WHILE)
}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 327 "lexer/pascal.l"
{
    RETURN_TOKEN(KWD_WITH)
}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 331 "lexer/pascal.l"
{
    RETURN_TOKEN(KWD_XOR)
}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 335 "lexer/pascal.l"
{
    RETURN_TOKEN(TYPE_INT)
}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 339 "lexer/pascal.l"
{
    RETURN_TOKEN(TYPE_INT_8)
}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 343 "lexer/pascal.l"
{
    RETURN_TOKEN(TYPE_INT_16)
}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 347 "lexer/pascal.l"
{
    RETURN_TOKEN(TYPE_INT_32)
}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 351 "lexer/pascal.l"
{
    RETURN_TOKEN(TYPE_INT_64)
}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 355 "lexer/pascal.l"
{
    RETURN_TOKEN(TYPE_UNSIGNED_INT_8)
}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 359 "lexer/pascal.l"
{
    RETURN_TOKEN(TYPE_UNSIGNED_INT_16)
}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 363 "lexer/pascal.l"
{
    RETURN_TOKEN(TYPE_UNSIGNED_INT_32)
}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 367 "lexer/pascal.l"
{
    RETURN_TOKEN(TYPE_UNSIGNED_INT_64)
}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 371 "lexer/pascal.l"
{
    RETURN_TOKEN(TYPE_BOOLEAN)
}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 375 "lexer/pascal.l"
{
    RETURN_TOKEN(TYPE_FLOAT)
}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 379 "lexer/pascal.l"
{
    RETURN_TOKEN(TYPE_FLOAT_16)
}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 383 "lexer/pascal.l"
{
    RETURN_TOKEN(TYPE_FLOAT_32)
}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 387 "lexer/pascal.l"
{
    RETURN_TOKEN(TYPE_CHAR)
}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 391 "lexer/pascal.l"
{
    RETURN_TOKEN(TYPE_STRING)
}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 395 "lexer/pascal.l"
{
    yylval = strdup(yytext);
    RETURN_TOKEN(LITERAL_INT)
}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 400 "lexer/pascal.l"
{
    yylval = strdup(yytext);
    RETURN_TOKEN(LITERAL_FALSE)
}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 405 "lexer/pascal.l"
{
    yylval = strdup(yytext);
    RETURN_TOKEN(LITERAL_CHAR)
}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 410 "lexer/pascal.l"
{
    yylval = strdup(yytext);
    RETURN_TOKEN(LITERAL_ESC_CHAR)
}
	YY_BREAK
case 71:
/* rule 71 can match eol */
YY_RULE_SETUP
#line 415 "lexer/pascal.l"
{
    yylval = strdup(yytext);
    RETURN_TOKEN(LITERAL_STR)
}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 420 "lexer/pascal.l"
{
    yylval = strdup(yytext);
    RETURN_TOKEN(LITERAL_TRUE)
}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 425 "lexer/pascal.l"
{
    yylval = strdup(yytext);
    RETURN_TOKEN(LITERAL_FALSE)
}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 430 "lexer/pascal.l"
{
    yylval = strdup(yytext);
    RETURN_TOKEN(IDENTIFIER)
}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 435 "lexer/pascal.l"
{
    RETURN_TOKEN(SYM_ADD)
}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 439 "lexer/pascal.l"
{
    RETURN_TOKEN(SYM_SUB)
}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 443 "lexer/pascal.l"
{
    RETURN_TOKEN(SYM_MUL)
}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 447 "lexer/pascal.l"
{
    RETURN_TOKEN(SYM_DIV)
}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 451 "lexer/pascal.l"
{
    RETURN_TOKEN(SYM_EQ)
}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 455 "lexer/pascal.l"
{
    RETURN_TOKEN(SYM_LT)
}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 459 "lexer/pascal.l"
{
    RETURN_TOKEN(SYM_GT)
}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 463 "lexer/pascal.l"
{
    RETURN_TOKEN(SYM_LBRAC)
}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 467 "lexer/pascal.l"
{
    RETURN_TOKEN(SYM_RBRAC)
}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 471 "lexer/pascal.l"
{
    RETURN_TOKEN(SYM_PERIOD)
}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 475 "lexer/pascal.l"
{
    RETURN_TOKEN(SYM_COMMA)
}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 479 "lexer/pascal.l"
{
    RETURN_TOKEN(SYM_COLON)
}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 483 "lexer/pascal.l"
{
    RETURN_TOKEN(SYM_SEMICOLON)
}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 487 "lexer/pascal.l"
{
    RETURN_TOKEN(SYM_AT)
}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 491 "lexer/pascal.l"
{
    RETURN_TOKEN(SYM_CARET)
}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 495 "lexer/pascal.l"
{
    RETURN_TOKEN(SYM_LPAREN)
}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 499 "lexer/pascal.l"
{
    RETURN_TOKEN(SYM_RPAREN)
}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 503 "lexer/pascal.l"
{
    RETURN_TOKEN(SYM_NE)
}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 507 "lexer/pascal.l"
{
    RETURN_TOKEN(SYM_LE)
}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 511 "lexer/pascal.l"
{
    RETURN_TOKEN(SYM_GE)
}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 515 "lexer/pascal.l"
{
    RETURN_TOKEN(SYM_ASSIGN)
}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 519 "lexer/pascal.l"
{
    RETURN_TOKEN(SYM_RANGE)
}
	YY_BREAK
case 97:
/* rule 97 can match eol */
YY_RULE_SETUP
#line 524 "lexer/pascal.l"
{}
	YY_BREAK
case 98:
/* rule 98 can match eol */
YY_RULE_SETUP
#line 526 "lexer/pascal.l"
{
    yycolumn = 1;
}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 529 "lexer/pascal.l"
{}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 531 "lexer/pascal.l"
{
    printf("unknown character %d\n", (int) yytext[0]);
    return yytext[0];
}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 535 "lexer/pascal.l"
ECHO;
	YY_BREAK
#line 1769 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 333 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 333 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 332);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		   
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n, i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 535 "lexer/pascal.l"



void yyerror(const char *s) {
    fprintf(stderr, "LexError: %s (at Line %d, Column%d)\n", s, yylloc->begin.line, yylloc->end.line);
}

#ifdef DEBUG_LEXER

int main() {
    yylex();
    return 0;
}

#endif
