#ifndef OPC_VISITOR_H
#define OPC_VISITOR_H

class ASTNode;
class ASTNameList;
class ASTExpressionList;
class ASTBinaryExpr;
class ASTUnaryExpr;
class ASTPropExpr;
class ASTConstValueExpr;
class ASTFuncCall;
class ASTIDExpr;
class ASTArrayExpr;
class ASTProgramHead;
class ASTRoutineHead;
class ASTRoutineBody;
class ASTRoutine;
class ASTProgram;
class ASTRoutinePart;
class ASTFuncProcBase;
class ASTFunctionDecl;
class ASTFunctionHead;
class ASTProcedureDecl;
class ASTProcedureHead;
class ASTParaDeclList;
class ASTParaTypeList;
class ASTVarParaList;
class ASTValParaList;
class ASTNonLabelStmt;
class ASTStmt;
class ASTStmtList;
class ASTAssignStmt;
class ASTProcStmt;
class ASTIfStmt;
class ASTElseClause;
class ASTRepeatStmt;
class ASTWhileStmt;
class ASTForStmt;
class ASTCaseStmt;
class ASTCaseExprList;
class ASTCaseExpr;
class ASTGotoStmt;
class ASTType;
class ASTSimpleTypeDecl;
class ASTArrayTypeDecl;
class ASTFieldDecl;
class ASTFieldDeclList;
class ASTRecordTypeDecl;
class ASTTypeDefinition;
class ASTTypeDeclList;
class ASTTypePart;
class ASTConstValue;
class ASTConstExprList;
class ASTConstExpr;
class ASTConstPart;
class ASTVarPart;
class ASTVarDeclList;
class ASTVarDecl;

class Visitor {
 public:
  virtual ~Visitor() = default;
  virtual void VisitASTNode(ASTNode* node)=0;
  virtual void VisitASTNameList(ASTNameList* node)=0;
  virtual void VisitASTExpressionList(ASTExpressionList* node)=0;
  virtual void VisitASTBinaryExpr(ASTBinaryExpr* node)=0;
  virtual void VisitASTUnaryExpr(ASTUnaryExpr* node)=0;
  virtual void VisitASTPropExpr(ASTPropExpr* node)=0;
  virtual void VisitASTConstValueExpr(ASTConstValueExpr* node)=0;
  virtual void VisitASTFuncCall(ASTFuncCall* node)=0;
  virtual void VisitASTIDExpr(ASTIDExpr* node)=0;
  virtual void VisitASTArrayExpr(ASTArrayExpr* node)=0;
  virtual void VisitASTProgramHead(ASTProgramHead* node)=0;
  virtual void VisitASTRoutineHead(ASTRoutineHead* node)=0;
  virtual void VisitASTRoutineBody(ASTRoutineBody* node)=0;
  virtual void VisitASTRoutine(ASTRoutine* node)=0;
  virtual void VisitASTProgram(ASTProgram* node)=0;
  virtual void VisitASTRoutinePart(ASTRoutinePart* node)=0;
  virtual void VisitASTFuncProcBase(ASTFuncProcBase* node)=0;
  virtual void VisitASTFunctionDecl(ASTFunctionDecl* node)=0;
  virtual void VisitASTFunctionHead(ASTFunctionHead* node)=0;
  virtual void VisitASTProcedureDecl(ASTProcedureDecl* node)=0;
  virtual void VisitASTProcedureHead(ASTProcedureHead* node)=0;
  virtual void VisitASTParaDeclList(ASTParaDeclList* node)=0;
  virtual void VisitASTParaTypeList(ASTParaTypeList* node)=0;
  virtual void VisitASTVarParaList(ASTVarParaList* node)=0;
  virtual void VisitASTValParaList(ASTValParaList* node)=0;
  virtual void VisitASTNonLabelStmt(ASTNonLabelStmt* node)=0;
  virtual void VisitASTStmt(ASTStmt* node)=0;
  virtual void VisitASTStmtList(ASTStmtList* node)=0;
  virtual void VisitASTAssignStmt(ASTAssignStmt* node)=0;
  virtual void VisitASTProcStmt(ASTProcStmt* node)=0;
  virtual void VisitASTIfStmt(ASTIfStmt* node)=0;
  virtual void VisitASTElseClause(ASTElseClause* node)=0;
  virtual void VisitASTRepeatStmt(ASTRepeatStmt* node)=0;
  virtual void VisitASTWhileStmt(ASTWhileStmt* node)=0;
  virtual void VisitASTForStmt(ASTForStmt* node)=0;
  virtual void VisitASTCaseStmt(ASTCaseStmt* node)=0;
  virtual void VisitASTCaseExprList(ASTCaseExprList* node)=0;
  virtual void VisitASTCaseExpr(ASTCaseExpr* node)=0;
  virtual void VisitASTGotoStmt(ASTGotoStmt* node)=0;
  virtual void VisitASTType(ASTType* node)=0;
  virtual void VisitASTSimpleTypeDecl(ASTSimpleTypeDecl* node)=0;
  virtual void VisitASTArrayTypeDecl(ASTArrayTypeDecl* node)=0;
  virtual void VisitASTFieldDecl(ASTFieldDecl* node)=0;
  virtual void VisitASTFieldDeclList(ASTFieldDeclList* node)=0;
  virtual void VisitASTRecordTypeDecl(ASTRecordTypeDecl* node)=0;
  virtual void VisitASTTypeDefinition(ASTTypeDefinition* node)=0;
  virtual void VisitASTTypeDeclList(ASTTypeDeclList* node)=0;
  virtual void VisitASTTypePart(ASTTypePart* node)=0;
  virtual void VisitASTConstValue(ASTConstValue* node)=0;
  virtual void VisitASTConstExprList(ASTConstExprList* node)=0;
  virtual void VisitASTConstExpr(ASTConstExpr* node)=0;
  virtual void VisitASTConstPart(ASTConstPart* node)=0;
  virtual void VisitASTVarPart(ASTVarPart* node)=0;
  virtual void VisitASTVarDeclList(ASTVarDeclList* node)=0;
  virtual void VisitASTVarDecl(ASTVarDecl* node)=0;

};

#endif  // OPC_VISITOR_H
